export { default as Contact } from './contact/Contact'
export { default as Home } from './home/Home'
export { default as Resources } from './resources/Resources'
export { default as Whoweare } from './whoweare/Whoweare'
export { default as Whowehelp } from './whowehelp/Whowehelp'